import "./globals.css";
import { Alegreya } from "next/font/google";

export const metadata = {
  title: "Galgotian Buddy",
  description: "Generated by create next app",
};

// Update to the new font
const font = Alegreya({ subsets: ["latin"], weight: "400" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
      </head>
      <body className={`${font.className} bg-gray-200`}>{children}</body>
    </html>
  );
}
