import "./globals.css";
import { Alegreya } from "next/font/google";

export const metadata = {
  title: "Shrey Shorts",
  description: "Generated by create next app",
};

// Update to the new font
const font = Alegreya({ subsets: ["latin"], weight: "400" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-gray-200`}>{children}</body>
    </html>
  );
}
